<a href="https://colab.research.google.com/github/Tanushree-233/Machine_Learning/blob/main/ML_hebbianAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

Y = np.array([[0],
              [0],
              [0],
              [1]])

# ----------------------------
# Initialize weights
# ----------------------------
input_size = X.shape[1]
output_size = Y.shape[1]

np.random.seed(42)
W = np.zeros((input_size, output_size))  # initialize weights to 0

# Learning rate
eta = 0.1

# ----------------------------
# Hebbian Learning
# ----------------------------
for epoch in range(1, 6):  # train for 5 iterations
    print(f"Epoch {epoch}")
    for x, y in zip(X, Y):
        # Compute weight change
        delta_W = eta * np.outer(x, y)
        # Update weights
        W += delta_W
        print(f"Input: {x}, Target: {y}, Weight change:\n{delta_W}\nUpdated Weights:\n{W}\n")


Epoch 1
Input: [0 0], Target: [0], Weight change:
[[0.]
 [0.]]
Updated Weights:
[[0.]
 [0.]]

Input: [0 1], Target: [0], Weight change:
[[0.]
 [0.]]
Updated Weights:
[[0.]
 [0.]]

Input: [1 0], Target: [0], Weight change:
[[0.]
 [0.]]
Updated Weights:
[[0.]
 [0.]]

Input: [1 1], Target: [1], Weight change:
[[0.1]
 [0.1]]
Updated Weights:
[[0.1]
 [0.1]]

Epoch 2
Input: [0 0], Target: [0], Weight change:
[[0.]
 [0.]]
Updated Weights:
[[0.1]
 [0.1]]

Input: [0 1], Target: [0], Weight change:
[[0.]
 [0.]]
Updated Weights:
[[0.1]
 [0.1]]

Input: [1 0], Target: [0], Weight change:
[[0.]
 [0.]]
Updated Weights:
[[0.1]
 [0.1]]

Input: [1 1], Target: [1], Weight change:
[[0.1]
 [0.1]]
Updated Weights:
[[0.2]
 [0.2]]

Epoch 3
Input: [0 0], Target: [0], Weight change:
[[0.]
 [0.]]
Updated Weights:
[[0.2]
 [0.2]]

Input: [0 1], Target: [0], Weight change:
[[0.]
 [0.]]
Updated Weights:
[[0.2]
 [0.2]]

Input: [1 0], Target: [0], Weight change:
[[0.]
 [0.]]
Updated Weights:
[[0.2]
 [0.2]]

Input: [1 